[package]
name = "eww-ctl"
version = "0.1.0"
edition = "2021"

[dependencies]
ocl = "0.19.7"
image = "0.25.5"
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
chrono = "0.4.39"
rodio = "0.20.1"
